sudo: required
services:
  - docker

jobs:
  include:
    - stage: testing
      env: 
        - COMPOSE_VERSION=1.23.2
      before_install:
        - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - npm install
      script: 
        - docker-compose -f docker-compose.yml -f docker-compose.test.yml run api-test
    - stage: build
      name: "Building and tagging an image"
      script: 
        - ./scripts/build.sh
    
    # - stage: deploy-test
    #   name: "Deploy to Heroku test environment"
    #   script: skip
    #   deploy:
    #     provider: script
    #     script: bash scripts/deploy.sh $TEST_CLUSTER_NAME $TEST_SERVICE_NAME
    #     on: 
    #       branch: test
    #       condition: $TRAVIS_BRANCH = test
      